name: Xcode - Build and Analyze

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        env:
          scheme: ${{ 'default' }}
        run: |
          make
